In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.formula.api as sm

In [4]:
player_stats_with_allstar = pd.read_csv("player_stats_with_allstar.csv")
player_stats_with_allstar.drop("Unnamed: 0", axis= 1, inplace=True)
player_stats_with_allstar

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Season,All Star
0,1,Alex Acker,SG,26,TOT,25,0,8.0,1.2,3.0,...,0.6,1.0,0.5,0.2,0.2,0.3,0.4,2.9,2009,0
1,1,Alex Acker,SG,26,DET,7,0,2.9,0.6,1.6,...,0.3,0.3,0.1,0.3,0.1,0.0,0.0,1.3,2009,0
2,1,Alex Acker,SG,26,LAC,18,0,9.9,1.4,3.6,...,0.8,1.2,0.6,0.2,0.2,0.4,0.5,3.5,2009,0
3,2,Hassan Adams,SG,24,TOR,12,0,4.3,0.3,1.1,...,0.5,0.6,0.1,0.1,0.1,0.3,0.3,0.9,2009,0
4,3,Arron Afflalo,SG,23,DET,74,8,16.7,1.8,4.1,...,1.4,1.8,0.6,0.4,0.2,0.6,1.9,4.9,2009,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9508,507,McKinley Wright IV,PG,24,DAL,20,1,10.3,1.2,2.5,...,1.0,1.3,1.9,0.4,0.2,0.6,0.9,2.9,2023,0
9509,508,Thaddeus Young,PF,34,TOR,50,9,15.5,2.1,3.8,...,1.8,3.2,1.5,1.1,0.1,0.8,1.7,4.8,2023,0
9510,509,Trae Young,PG,24,ATL,55,55,35.3,8.5,19.9,...,2.2,2.9,10.1,1.0,0.2,4.1,1.5,27.1,2023,1
9511,510,Cody Zeller,C,30,MIA,4,0,15.5,2.0,3.3,...,1.5,2.8,1.0,0.3,0.8,0.5,2.8,6.0,2023,0
9512,511,Ivica Zubac,C,25,LAC,60,60,29.4,4.0,6.5,...,6.8,10.1,1.1,0.4,1.3,1.7,3.0,10.2,2023,0

In [8]:
len(player_stats_with_allstar["Player"].unique())

1714

In [12]:
sum(player_stats_with_allstar["All Star"])

353

In [25]:
player_stats_with_allstar.groupby(by="Season").sum()["All Star"]

Season
2009    19
2010    20
2011    21
2012    21
2013    21
2014    23
2015    25
2016    24
2017    27
2018    26
2019    25
2020    23
2021    26
2022    27
2023    25
Name: All Star, dtype: int64

In [34]:
season_player_grouped = player_stats_with_allstar.groupby(["Season", "Player"]).count()
season_player_grouped

                        Rk  Pos  Age  Tm  G  GS  MP  FG  FGA  FG%  ...  ORB  \
Season Player                                                      ...
2009   Aaron Brooks      1    1    1   1  1   1   1   1    1    1  ...    1
       Aaron Gray        1    1    1   1  1   1   1   1    1    1  ...    1
       Acie Law          1    1    1   1  1   1   1   1    1    1  ...    1
       Adam Morrison     3    3    3   3  3   3   3   3    3    3  ...    3
       Adonal Foyle      3    3    3   3  3   3   3   3    3    2  ...    3
...                     ..  ...  ...  .. ..  ..  ..  ..  ...  ...  ...  ...
2023   Zach Collins      1    1    1   1  1   1   1   1    1    1  ...    1
       Zach LaVine       1    1    1   1  1   1   1   1    1    1  ...    1
       Zeke Nnaji        1    1    1   1  1   1   1   1    1    1  ...    1
       Ziaire Williams   1    1    1   1  1   1   1   1    1    1  ...    1
       Zion Williamson   1    1    1   1  1   1   1   1    1    1  ...    1

                        DRB  TRB  AST  STL  BLK  TOV  PF  PTS  All Star
Season Player
2009   Aaron Brooks       1    1    1    1    1    1   1    1         1
       Aaron Gray         1    1    1    1    1    1   1    1         1
       Acie Law           1    1    1    1    1    1   1    1         1
       Adam Morrison      3    3    3    3    3    3   3    3         3
       Adonal Foyle       3    3    3    3    3    3   3    3         3
...                     ...  ...  ...  ...  ...  ...  ..  ...       ...
2023   Zach Collins       1    1    1    1    1    1   1    1         1
       Zach LaVine        1    1    1    1    1    1   1    1         1
       Zeke Nnaji         1    1    1    1    1    1   1    1         1
       Ziaire Williams    1    1    1    1    1    1   1    1         1
       Zion Williamson    1    1    1    1    1    1   1    1         1

[7474 rows x 30 columns]

In [36]:
season_player_grouped[season_player_grouped["All Star"] > 1]

                       Rk  Pos  Age  Tm  G  GS  MP  FG  FGA  FG%  ...  ORB  \
Season Player                                                     ...
2009   Adam Morrison    3    3    3   3  3   3   3   3    3    3  ...    3
       Adonal Foyle     3    3    3   3  3   3   3   3    3    2  ...    3
       Al Harrington    3    3    3   3  3   3   3   3    3    3  ...    3
       Alex Acker       3    3    3   3  3   3   3   3    3    3  ...    3
       Allen Iverson*   3    3    3   3  3   3   3   3    3    3  ...    3
...                    ..  ...  ...  .. ..  ..  ..  ..  ...  ...  ...  ...
2023   T.J. Warren      3    3    3   3  3   3   3   3    3    3  ...    3
       Terrence Ross    3    3    3   3  3   3   3   3    3    3  ...    3
       Terry Taylor     3    3    3   3  3   3   3   3    3    3  ...    3
       Thomas Bryant    3    3    3   3  3   3   3   3    3    3  ...    3
       Will Barton      3    3    3   3  3   3   3   3    3    3  ...    3

                       DRB  TRB  AST  STL  BLK  TOV  PF  PTS  All Star
Season Player
2009   Adam Morrison     3    3    3    3    3    3   3    3         3
       Adonal Foyle      3    3    3    3    3    3   3    3         3
       Al Harrington     3    3    3    3    3    3   3    3         3
       Alex Acker        3    3    3    3    3    3   3    3         3
       Allen Iverson*    3    3    3    3    3    3   3    3         3
...                    ...  ...  ...  ...  ...  ...  ..  ...       ...
2023   T.J. Warren       3    3    3    3    3    3   3    3         3
       Terrence Ross     3    3    3    3    3    3   3    3         3
       Terry Taylor      3    3    3    3    3    3   3    3         3
       Thomas Bryant     3    3    3    3    3    3   3    3         3
       Will Barton       3    3    3    3    3    3   3    3         3

[987 rows x 30 columns]

In [38]:
player_stats_with_allstar[player_stats_with_allstar["Player"] == "Alex Acker"]

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Season,All Star
0,1,Alex Acker,SG,26,TOT,25,0,8.0,1.2,3.0,...,0.6,1.0,0.5,0.2,0.2,0.3,0.4,2.9,2009,0
1,1,Alex Acker,SG,26,DET,7,0,2.9,0.6,1.6,...,0.3,0.3,0.1,0.3,0.1,0.0,0.0,1.3,2009,0
2,1,Alex Acker,SG,26,LAC,18,0,9.9,1.4,3.6,...,0.8,1.2,0.6,0.2,0.2,0.4,0.5,3.5,2009,0